### ISSUE TITLE
patch forward from mrtg tracker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sleinen/snmp-session#4]
```
http://oss.oetiker.ch/mrtg-trac/ticket/93
```

Original issue reported on code.google.com by `oeti...@gmail.com` on 11 Jun 2010 at 3:07

**Comment by RolandRosenfeld** [comment]
As far as I can see, this was fixed in commit 68dc51bb027e4d56990ef141837b65238fdd6900.

**Comment by sleinen** [comment]
Thanks @RolandRosenfeld and @michal-josef-spacek! Closing the issue.
